export const STORE_LOCATOR_ALGOLIA_INDEX_NAME = `${process.env.NEXT_PUBLIC_STORE_LOCATOR_ALGOLIA_INDEX_NAME}`
export const STORE_LOCATOR_ALGOLIA_APP_ID = `${process.env.NEXT_PUBLIC_STORE_LOCATOR_ALGOLIA_APP_ID}`
export const STORE_LOCATOR_ALGOLIA_API_KEY = `${process.env.NEXT_PUBLIC_STORE_LOCATOR_ALGOLIA_API_KEY}`
