export const ANONYMOUS_USER_COOKIE = 'anonymous_user'

export const COMMERCETOOLS_PROJECT_KEY =
  process.env.NEXT_PUBLIC_COMMERCETOOLS_PROJECT_KEY ?? ''

export const COMMERCETOOLS_HOST =
  process.env.NEXT_PUBLIC_COMMERCETOOLS_HOST ?? ''

export const COMMERCETOOLS_ADMIN_CLIENT_ID =
  process.env.SERVER_COMMERCETOOLS_ADMIN_CLIENT_ID ?? ''

export const COMMERCETOOLS_ADMIN_CLIENT_SECRET =
  process.env.SERVER_COMMERCETOOLS_ADMIN_CLIENT_SECRET ?? ''

export const COMMERCETOOLS_USER_SCOPED_CLIENT_ID =
  process.env.SERVER_COMMERCETOOLS_USER_SCOPED_CLIENT_ID ?? ''

export const COMMERCETOOLS_USER_SCOPED_CLIENT_SECRET =
  process.env.SERVER_COMMERCETOOLS_USER_SCOPED_CLIENT_SECRET ?? ''
