export const COMMERCETOOLS_PROJECT_KEY =
  process.env.NEXT_PUBLIC_COMMERCETOOLS_PROJECT_KEY ?? ''
export const COMMERCETOOLS_CLIENT_ID =
  process.env.NEXT_PUBLIC_COMMERCETOOLS_CLIENT_ID ?? ''
export const COMMERCETOOLS_CLIENT_SECRET =
  process.env.NEXT_PUBLIC_COMMERCETOOLS_CLIENT_SECRET ?? ''
export const COMMERCETOOLS_HOST =
  process.env.NEXT_PUBLIC_COMMERCETOOLS_HOST ?? ''
