name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: pnpm install
        uses: pnpm/action-setup@v4
        with:
          version: 8.3.1

      - name: Install Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: TypeScript
        run: pnpm ts

      - name: Lint
        run: pnpm lint
